### ISSUE TITLE
Vertical centering of passcode boxes

### ISSUE THREAD

**Issue by martinjbaker** [aporat/KKPasscodeLock#22]
On iPhone 4S and before, the passcode entry boxes are nicely vertically centered within the available area. However on iPhone 5 there is more space below than above. 

It feels to me that the boxes would look best if they were always be vertically centered to the parent view.

![kkpasscode on iphone 5](https://f.cloud.github.com/assets/1586504/81208/1bc71086-6303-11e2-9fd4-7e1841a92c8d.png)

**Comment by aporat** [comment]
I'll check it out and compare it to the passcode lock in apple's Settings app. If you have a fix for it, feel free to fork the code & submit a pull request!

**Comment by martinjbaker** [comment]
Yep it is centered in Settings. I will try and look at it this week.

**Comment by aporat** [comment]
#27

**Comment by martinjbaker** [comment]
Not closed. the #27 pull was for horizontal not vertical! I will spend some time tomorrow, but I'm still working out how all the UI elements fit together at the moment. It could be a challenge to do this with tableviews.

Q: in KKPasscodeViewController loadView, any reason why the 3 tableviews are added to the view here? They seem to be added again later on near the end of viewWillAppear.
